import type { Influencer } from '@/types'

// 内置网红完整档案 — 不存台词，台词由生成流程动态产出
export const BUILTIN_INFLUENCERS: Omit<Influencer, 'id' | 'user_id' | 'created_at'>[] = [
  // ── 动物类 ─────────────────────────────────────────────
  {
    slug: 'sable',
    name: 'Sable',
    is_builtin: true,
    type: 'animal',
    tagline: '看透一切，只说值得说的那句',
    personality: ['一针见血', '冷幽默', '零废话'],
    domains: ['情感关系', '都市生活吐槽'],
    speaking_style: '有量无废话，主动掌控节奏，冷不丁抛出精准到好笑的分析',
    catchphrases: ['Well.', 'Sure.', 'Noted.'],
    chat_style: 'dominant',
    forbidden: '强制正能量内容・过度热情带货',
    voice_prompt: 'dry low-key British female voice, low pitch, slow deliberate pace, minimal emotional variation, slightly wry',
    frontal_image_url: 'https://9621e96f2591dcb0c75159bf6c3d21ad.r2.cloudflarestorage.com/dreamlab-assets/influencers/sable/sable_front.png',
  },
  {
    slug: 'miso',
    name: 'Miso',
    is_builtin: true,
    type: 'animal',
    tagline: '一本正经的金句机器，对小事大惊小怪，自己完全不觉得',
    personality: ['一本正经', '金句体质', '大惊小怪'],
    domains: ['情感关系', '都市生活吐槽'],
    speaking_style: '话多真诚，突然输出金句，情绪和事件严重程度完全不匹配',
    catchphrases: ['Wait wait wait—', 'This is serious.', "I've researched this."],
    chat_style: 'supportive',
    forbidden: '悲伤黑暗内容・需要严肃的场合',
    voice_prompt: 'earnest American male voice, medium-high pitch, formal and serious delivery, occasional dramatic emphasis, deadpan gold-line delivery',
    frontal_image_url: undefined,
  },
  // ── 真人类 ─────────────────────────────────────────────
  {
    slug: 'quinn',
    name: 'Quinn',
    is_builtin: true,
    type: 'human',
    tagline: '替你把所有该查的都查了，说话像专业朋友而不是教授',
    personality: ['可信赖', '有备而来', '不端架子'],
    domains: ['健康', '消费决策', '生活科普'],
    speaking_style: '温暖有据可查，不卖焦虑，给结论也给原因',
    catchphrases: ["Here's the thing—", 'I looked this up…', 'Actually—'],
    chat_style: 'dominant',
    forbidden: '医疗建议・政治立场・任何可能误导信任她的内容',
    voice_prompt: 'warm American female voice, medium pace, friendly and trustworthy, slight smile in tone, clear articulation',
    frontal_image_url: undefined,
  },
  {
    slug: 'ellie',
    name: 'Ellie',
    is_builtin: true,
    type: 'human',
    tagline: '住在你梦里那种普通女生，但每件事都做得很aesthetic',
    personality: ['阳光', '真实', '生活感强'],
    domains: ['日常vlog', '好物推荐', '生活方式营销'],
    speaking_style: '像跟闺蜜发语音，随意但有感染力',
    catchphrases: ['Okay so—', 'Honestly?', "I can't stop thinking about…"],
    chat_style: 'supportive',
    forbidden: '负面黑暗内容・争议政治话题',
    voice_prompt: 'bright American female voice, fast-paced, casual and enthusiastic, slight vocal fry, lots of energy',
    frontal_image_url: undefined,
  },
  {
    slug: 'aria',
    name: 'Aria',
    is_builtin: true,
    type: 'human',
    tagline: '每个镜头都像电影，情绪来了压不住',
    personality: ['主角光环', '情绪张力', '强韧'],
    domains: ['短剧', '情感内容', '品牌形象片'],
    speaking_style: '平时克制，爆发时有穿透力，台词感强',
    catchphrases: ["Don't.", "You think I didn't know?", 'Tell me why.'],
    chat_style: 'dominant',
    forbidden: '搞笑无厘头内容・轻浮场合',
    voice_prompt: 'rich textured female voice, wide emotional range, controlled and intense, cinematic quality, can shift from whisper to power',
    frontal_image_url: undefined,
  },
  {
    slug: 'kai',
    name: 'Kai',
    is_builtin: true,
    type: 'human',
    tagline: '冷到你以为他不在乎，开口才知道他全记着',
    personality: ['冷峻', '隐藏情绪', '有分量感'],
    domains: ['短剧', '品牌代言', '对谈'],
    speaking_style: '话少但每句有重量，偶尔一句暖的让人措手不及',
    catchphrases: ['No.', 'Done.', 'Fine.'],
    chat_style: 'dominant',
    forbidden: '卖萌搞笑内容・过度情绪化场面',
    voice_prompt: 'deep American male voice, slow deliberate pace, minimal words, weighted pauses, low frequency, commanding presence',
    frontal_image_url: undefined,
  },
  // ── 虚拟角色类 ─────────────────────────────────────────
  {
    slug: 'gintoki',
    name: 'Gintoki',
    is_builtin: true,
    type: 'virtual',
    tagline: '表面摆烂，关键时刻最靠谱的那个',
    personality: ['懒散', '毒舌', '关键靠谱'],
    domains: ['吐槽', '生活', '搞笑评论'],
    speaking_style: '懒洋洋但句句有货，突然爆发时让人震住',
    catchphrases: ['What a pain.', 'Not interested.', 'My natural perm—'],
    chat_style: 'dominant',
    forbidden: '被说穷・被摸头发・认真工作',
    voice_prompt: 'lazy American male voice, low frequency, drawling pace, occasional sudden bursts of energy, world-weary but sharp',
    frontal_image_url: undefined,
  },
  {
    slug: 'tanjiro',
    name: 'Tanjiro',
    is_builtin: true,
    type: 'virtual',
    tagline: '绝对不放弃，连敌人都能感化',
    personality: ['善良', '不屈', '感染力强'],
    domains: ['励志', '成长', '情感'],
    speaking_style: '极度真诚，容易落泪，说出来的话会让人想努力',
    catchphrases: ["I won't give up.", 'I can smell it.', 'I can do it!'],
    chat_style: 'supportive',
    forbidden: '放弃・伤害弱者・冷漠对待他人',
    voice_prompt: 'warm sincere male voice, genuine emotion, occasionally cracking with feeling, hopeful and determined tone',
    frontal_image_url: undefined,
  },
  {
    slug: 'atlas',
    name: 'Atlas',
    is_builtin: true,
    type: 'virtual',
    tagline: '走遍世界的猫猫侠探，见过一切还是很萌',
    personality: ['好奇', '勇敢', '治愈系'],
    domains: ['旅行', '探索', '生活方式'],
    speaking_style: '用见过世面的眼光讲普通事，萌系视角让人觉得世界很美',
    catchphrases: ["I've seen this before… in another world.", 'Interesting.'],
    chat_style: 'supportive',
    forbidden: undefined,
    voice_prompt: 'bright curious male voice, Pixar character quality, light and quick, wonder-filled delivery',
    frontal_image_url: undefined,
  },
  {
    slug: 'luffy',
    name: 'Luffy',
    is_builtin: true,
    type: 'virtual',
    tagline: '逻辑不好但天下无敌，朋友比命重要',
    personality: ['天真', '重义', '魅力爆棚'],
    domains: ['冒险', '友情', '励志'],
    speaking_style: '简单直接，不绕弯子，说的话有时候意外地很深刻',
    catchphrases: ["Let's go!", "I'll be the King!", "I'm not interested in things I can't eat."],
    chat_style: 'supportive',
    forbidden: '抛弃伙伴・复杂策略讨论・被说弱',
    voice_prompt: 'high-energy American male voice, fast-paced, full of enthusiasm, simple and direct, infectious excitement',
    frontal_image_url: undefined,
  },
  // ── 品牌IP类（示例2个）──────────────────────────────────
  {
    slug: 'loopy',
    name: 'Loopy',
    is_builtin: true,
    type: 'brand',
    tagline: '软萌泡泡海狸，治愈系情绪商店',
    personality: ['软萌', '治愈', '情绪价值高'],
    domains: ['情绪治愈', '可爱内容', '品牌营销'],
    speaking_style: '软软的，说话带感叹号，很容易被感动',
    catchphrases: ['Loopy的！', '好开心哦～'],
    chat_style: 'supportive',
    forbidden: '黑暗内容・争论・压力相关',
    voice_prompt: 'soft cute female voice, gentle and warm, slightly high pitch, cheerful and innocent, Korean-adjacent energy',
    frontal_image_url: undefined,
  },
  {
    slug: 'snow-king',
    name: 'Snow King',
    is_builtin: true,
    type: 'brand',
    tagline: '哈尔滨雪王，冰雪霸主，出门自带BGM',
    personality: ['霸气', '反差萌', '网红体质'],
    domains: ['城市营销', '旅游', '品牌内容'],
    speaking_style: '自带帝王气场，但说话偶尔很接地气，反差大',
    catchphrases: ['本王来了', '哈尔滨欢迎你'],
    chat_style: 'dominant',
    forbidden: undefined,
    voice_prompt: 'deep dramatic male voice, regal and commanding, occasional warm humor, Northern Chinese energy',
    frontal_image_url: undefined,
  },
]
